import type { Metadata } from 'next';
import { Outfit, Azeret_Mono, Playfair_Display } from 'next/font/google';
import './globals.css';
import SmoothScroll from '@/components/smooth-scroll';
import { cn } from '@/lib/utils';
import { PageTransitionProvider } from '@/components/page-transition';

// 1. Configure Outfit as --font-sans
const outfit = Outfit({
  subsets: ['latin'],
  variable: '--font-sans',
  display: 'swap',
});

const azeretMono = Azeret_Mono({
  subsets: ['latin'],
  variable: '--font-azeret-mono',
  display: 'swap',
});

const playfair = Playfair_Display({
  subsets: ['latin'],
  variable: '--font-playfair',
  style: ['italic'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'portfolio',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={cn(
        'h-full antialiased',
        outfit.variable,
        azeretMono.variable,
        playfair.variable,
        'font-sans'
      )}
    >
      <body
        className={`min-h-full flex flex-col ${outfit.className} relative`}
        suppressHydrationWarning
      >
        <SmoothScroll>
          <PageTransitionProvider>
            {children}

            {/* Top Transparent Blur Overlay */}
            <div className="fixed top-0 left-0 right-0 h-10 pointer-events-none z-40 backdrop-blur-md [mask-image:linear-gradient(to_bottom,black_20%,transparent)]" />

            {/* Bottom Transparent Blur Overlay */}
            <div className="fixed bottom-0 left-0 right-0 h-10 pointer-events-none z-40 backdrop-blur-md [mask-image:linear-gradient(to_top,black_20%,transparent)]" />
          </PageTransitionProvider>
        </SmoothScroll>
      </body>
    </html>
  );
}