import type { Metadata } from 'next';
import { Outfit, Azeret_Mono, Playfair_Display, Inter } from 'next/font/google';
import './globals.css';
import SmoothScroll from '@/components/smooth-scroll';
import { cn } from "@/lib/utils";

const inter = Inter({subsets:['latin'],variable:'--font-sans'});


// 1. Configure font instances
const outfit = Outfit({
  subsets: ['latin'],
  variable: '--font-outfit',
  display: 'swap',
});

const azeretMono = Azeret_Mono({
  subsets: ['latin'],
  variable: '--font-azeret-mono',
  display: 'swap',
});

const playfair = Playfair_Display({
  subsets: ['latin'],
  variable: '--font-playfair',
  style: ['italic'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'portfolio',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang='en'
      className={cn("h-full", "antialiased", outfit.variable, azeretMono.variable, playfair.variable, "font-sans", inter.variable)}
    >
      <body className={`min-h-full flex flex-col ${outfit.className}`}>
        <SmoothScroll>{children}</SmoothScroll>
      </body>
    </html>
  );
}
